first/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired



class PostForm(FlaskForm):
    title = StringField('Title', validators = [DataRequired()])
    content = TextAreaField('Content', validators = [DataRequired()])
    submit = SubmitField('Post')

first/posts/routes.py
from flask import render_template, flash, redirect, url_for, request, abort, Blueprint
from first import db
from first.posts.forms import  PostForm
from first.model import  Post
from flask_login import current_user, login_required



posts = Blueprint('posts', __name__)

@posts.route('/post/new', methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data, content=form.content.data, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('Your post hasbeen created!', 'success')
        return redirect(url_for('main.community'))
    return render_template('create_post.html', title = 'New Post', form=form, legend='New Post')

@posts.route('/post/<int:post_id>')
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('post.html', title=post.title, post = post)

@posts.route('/post/<int:post_id>/update', methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash('Your post has been updated!', 'success')
        return redirect(url_for('posts.post', post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
    return render_template('create_post.html', title = 'Update Post',
                            form=form, legend='Update Post')

@posts.route('/post/<int:post_id>/delete', methods=['GET', 'POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Your post has been deleted!', 'success')
    return redirect(url_for('main.community'))

first/users/routes.py
import os
import secrets
from PIL import Image
from flask import render_template, flash, redirect, url_for, request, abort, Blueprint
from first import  db, bcrypt, mail
from flask_sqlalchemy import SQLAlchemy
from first.users.forms import RegistrationForm, LoginForm, UpdateAccountForm, ResetPasswordForm, RequestResetForm
from first.model import User, Post
from flask_login import login_user, current_user, logout_user, login_required
from flask_mail import Message
from first.users.utils import save_picture, send_reset_email

users = Blueprint('users', __name__)

@users.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return render_template("index.html")
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash(f'Account created. You are able to login now!', 'success')
        return redirect(url_for('users.login'))
    return render_template ("register.html", title = 'Register', form=form)

@users.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return render_template("index.html")
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            flash('You have been logged in', 'success')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Log in unsuccessful', 'danger')
    return render_template ("login.html", title = 'Login', form=form)

@users.route('/logout')
def logout():
    logout_user()
    return render_template("index.html")

@users.route('/account', methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated!','success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename = 'profile_pic/' + current_user.image_file)
    return render_template('account.html', title='Account', image_file=image_file, form=form)


@users.route('/user/<string:username>')
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user)\
        .order_by(Post.date_posted.desc())\
        .paginate(page=page, per_page=5)
    return render_template ("user_posts.html", posts=posts, user=user)



@users.route('/reset_password', methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return render_template("index.html")
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent to you', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)

@users.route('/reset_password/<token>', methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return render_template("index.html")
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired Token', 'warning')
        return redirect(url_for('users.reset_request'))
    
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash(f'Your password has been reset. You are able to login now!', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)

first/templates/account.html
{%extends "secondback.html"%}
{%block content%}

<div class="content-section">
   <div class="media">
      <img class = "rounded-circle account-img" src="{{ image_file }}" alt="##">
      <div class="media-body">
         <h2 class="account-heading">{{ current_user.username }}</h2>
         <p class="text-secondary">{{ current_user.email }}</p>
      </div>
   </div>
   <div class="contact">
      <div class="container">
         <div class="row ">
              <div class="col-md-10 offset-md-1">
                  <div class="row ">
                      <div class="col-md-12">
                      <div class="titlepage text_align_center">
                          <h2><span class="blue_light">Account Info</span></h2>
                      </div>
                      </div>
                      <form method = "POST" action="" enctype="multipart/form-data" class="main_form" >
                          {{ form.hidden_tag()}}                
                      
                          <div class="col-md-12">
                              {{ form.username.label(class = "form-control-label")}}
  
                              {% if form.username.errors %}
                                  {{ form.username(class = "form-control form-control-lg is-invalid")}}
                                  <div class="invalid-feedback">
                                      {% for error in form.username.errors %}
                                          <span>{{ error }}</span>
  
                                      {%endfor%}
  
  
                                  </div>
                              {% else%}
                                  {{ form.username(class = "form-control form-control-lg")}}
                              {%endif%}
                              
  
                          </div>
                          <div class="col-md-12">
                              {{form.email.label(class = "form-control-label")}}
                              
                              {%if form.email.errors %}
                                  {{ form.email(class = "form-control form-control-lg is-invalid")}}
                                  <div class="invalid-feedback">
                                      {%for error in form.email.errors %}
                                          <span>{{ error }}</span>
  
                                      {%endfor%}
  
  
                                  </div>
                              {%else%}
                                  {{form.email(class = "form-control form-control-lg")}}
                              {%endif%}                        
  
                          </div>
                          <div class="form-group">
                              {{ form.picture.label()}}
                              {{ form.picture(class="form-control-file")}}
                              {% if form.picture.errors %}
                                 {%for error in form.picture.errors %}
                                 <span class="text-danger">{{ error }}</span></br>

                                 {%endfor%}

                              {%endif%}
                           
                          </div>
                          <div class="col-md-12">
                              <button class="send_btn">Update</button>
                          </div>
  
                          
  
                      </form>
  
  
                  </div>
              </div>
          </div>
      </div>
  </div>    
  
</div>
{%endblock%}

first/templates/community.html
{%extends "secondback.html"%}
{%block content%}
    {% for post in posts.items%}
    <article class="media content-section">
        <img src="{{ url_for('static', filename = 'profile_pic/' + post.author.image_file) }}" alt="##" class="rounded-circle article-img">
        <div class="media-body">
            <div class="article-metadata">
                <a href="{{ url_for('users.user_posts', username=post.author.username)}}" class="mr-2">{{ post.author.username }}</a>
                <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
            </div>
            <h2><a href="{{ url_for('posts.post', post_id=post.id)}}" class="article-title">{{ post.title}}</a></h2>
            <p class="article-content">{{ post.content}}</p>
        </div>
    </article>
    {%endfor%}
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
    {%if page_num%}
        {% if posts.page == page_num%}
        <a class="btn btn-info mb-4" href="{{ url_for('main.community', page = page_num)}}"></a>
        {%else%}
        <a class="btn btn-outline-info mb-4" href="{{ url_for('main.community', page = page_num)}}"></a>
        {%endif%}
    {%else%}
    ...
    {%endif%}
    {%endfor%}     
{%endblock%}

first/templates/contact.html
{%extends "secondback.html"%}
{%block content%}
     
      <!-- contact -->
      <div class="contact">
         <div class="container">
            <div class="row ">
               <div class="col-md-12">
                  <div class="titlepage text_align_center">
                     <h2>Contact <span class="blue_light">Us</span></h2>
                  </div>
               </div>
               <div class="col-md-10 offset-md-1">
                  <form id="request" class="main_form">
                     <div class="row">
                        <div class="col-md-12 ">
                           <input class="contactus" placeholder="Name" type="type" name=" Name"> 
                        </div>
                        <div class="col-md-12">
                           <input class="contactus" placeholder="Phone number" type="type" name="Phone Number">                          
                        </div>
                        <div class="col-md-12">
                           <input class="contactus" placeholder="Your Email" type="type" name="Email">                          
                        </div>
                        <div class="col-md-12">
                           <textarea class="textarea" placeholder="Message" type="type" Message="Name"></textarea>
                        </div>
                        <div class="col-md-12">
                           <button class="send_btn">Submit Now</button>
                        </div>
                     </div>
                  </form>
               </div>
            </div>
         </div>
      </div>
      <!-- contact -->
      
 {%endblock%}

first/templates/create_post.html
{%extends "secondback.html"%}
{%block content%}
<div class="contact">
    <div class="container">
       <div class="row ">
            <div class="col-md-10 offset-md-1">
                <div class="row ">
                    <div class="col-md-12">
                    <div class="titlepage text_align_center">
                        <h2><span class="blue_light">{{legend}}</span></h2>
                    </div>
                    </div>
                    <form method = "POST" action="" class="main_form" >
                        {{ form.hidden_tag()}}
                
                    
                        
                        <div class="col-md-12">
                            {{form.title.label(class = "form-control-label")}}
                            {%if form.title.errors %}
                            {{ form.title(class = "form-control form-control-lg is-invalid")}}
                            <div class="invalid-feedback">
                                {%for error in form.title.errors %}
                                    <span>{{ error }}</span>

                                {%endfor%}


                            </div>
                        {%else%}
                            {{form.title(class = "form-control form-control-lg")}}
                        {%endif%}
                        </div>

                        <div class="col-md-12">
                            {{form.content.label(class = "form-control-label")}}
                            {%if form.content.errors %}
                                {{ form.content(class = "form-control form-control-lg is-invalid")}}
                                <div class="invalid-feedback">
                                    {%for error in form.content.errors %}
                                        <span>{{ error }}</span>

                                    {%endfor%}


                                </div>
                            {%else%}
                                {{form.content(class = "form-control form-control-lg")}}
                            {%endif%}

                        </div>
                       

                        <div class="col-md-12">
                            <button class="send_btn">Post</button>
                        </div>

                       
                        

                        

                    </form>
                    


                </div>
            </div>
        </div>
    </div>
    
</div>    
{%endblock%}

first/templates/domain.html
{%extends "secondback.html"%}
{%block content%}
      
      <!-- domain -->
      <div class="domain">
         <div class="container">
            <div class="row">
               <div class="col-md-12">
                  <div class="titlepage text_align_center">
                     <h2>all starts with  <span class="blue_light">a domain</span></h2>
                  </div>
               </div>
            </div>
            <div class="row">
               <div class="col-md-10 offset-md-1">
                  <div class="form">
                     <div class="searchbar">
                        <input class="search_input" type="text" name="" placeholder="Search Domain">
                        <a href="#" class="search_icon"><i class="fa fa-search" aria-hidden="true"></i>
                        </a>
                     </div>
                  </div>
               </div>
               <div class="col-md-10 offset-md-1">
                  <div class="domain_bg">
                     <div class="row">
                        <div class="col-sm-2">
                           <div class="domain-price">
                              <strong>Domain <br> Per Year</strong>
                           </div>
                        </div>
                        <div class="col-sm-10">
                           <div class="domain-price_main ">
                              <div class="domain-price">
                                 <span>com.</span>
                                 <strong>$22.999</strong>
                              </div>
                              <div class="domain-price">
                                 <span>com.</span>
                                 <strong>$22.999</strong>
                              </div>
                              <div class="domain-price">
                                 <span>com.</span>
                                 <strong>$22.999</strong>
                              </div>
                              <div class="domain-price">
                                 <span>com.</span>
                                 <strong>$22.999</strong>
                              </div>
                              <div class="domain-price">
                                 <span>com.</span>
                                 <strong>$22.999</strong>
                              </div>
                              <div class="domain-price">
                                 <span>com.</span>
                                 <strong>$22.999</strong>
                              </div>
                           </div>
                        </div>
                     </div>
                     <a class="read_more" href="domain">See More</a>
                  </div>
               </div>
            </div>
         </div>
      </div>
      <!-- end domain -->
      
{%endblock%}

first/templates/hosting.html
{%extends "secondback.html"%}
{%block content%}
      <!-- order -->
      <div class="order">
         <div class="container">
            <div class="row">
               <div class="col-md-8 offset-md-2">
                  <div class="titlepage text_align_center">
                     <h2>Check Out Awesome Plans, <br> <span class="blue_light">Order Now</span></h2>
                     <p>dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui 
                        officia deserunt mollit anim id est laborum."
                     </p>
                  </div>
               </div>
            </div>
            <div class="row">
               <div class="col-md-4">
                  <div id="ho_co" class="order-box_main">
                     <div class="order-box text_align_center">
                        <h3>Shared Hosting</h3>
                        <p>STARTING  <span>$9</span> PER MONTH</p>
                        <a href="Javascript:void(0)">Personal use</a>
                        <ul class="supp">
                           <li>Unlimited projects</li>
                           <li>24/7 support</li>
                           <li>Personal use</li>
                           <li>Unlimited projects</li>
                           <li>24/7 support</li>
                        </ul>
                     </div>
                     <a class="read_more" href="Javascript:void(0)">Buy Now</a>
                  </div>
               </div>
               <div class="col-md-4">
                  <div id="ho_co" class="order-box_main">
                     <div class="order-box text_align_center">
                        <h3>Reseller Hosting</h3>
                        <p>STARTING  <span>$9</span> PER MONTH</p>
                        <a href="Javascript:void(0)">Personal use</a>
                        <ul class="supp">
                           <li>Unlimited projects</li>
                           <li>24/7 support</li>
                           <li>Personal use</li>
                           <li>Unlimited projects</li>
                           <li>24/7 support</li>
                        </ul>
                     </div>
                     <a class="read_more" href="Javascript:void(0)">Buy Now</a>
                  </div>
               </div>
               <div class="col-md-4">
                  <div id="ho_co" class="order-box_main">
                     <div class="order-box text_align_center">
                        <h3>Dedicated Servers</h3>
                        <p>STARTING  <span>$9</span> PER MONTH</p>
                        <a href="Javascript:void(0)">Personal use</a>
                        <ul class="supp">
                           <li>Unlimited projects</li>
                           <li>24/7 support</li>
                           <li>Personal use</li>
                           <li>Unlimited projects</li>
                           <li>24/7 support</li>
                        </ul>
                     </div>
                     <a class="read_more" href="Javascript:void(0)">Buy Now</a>
                  </div>
               </div>
            </div>
         </div>
      </div>
      <!-- end order -->
{%endblock%}

first/templates/index.html
{%extends "secondback.html"%}
{%block content%}
     

      <!-- top -->
      <div class="full_bg">
         <div class="slider_main">
            <div class="container">
               <div class="row">
                  <div class="col-md-12">
                     <!-- carousel code -->
                     <div id="banner1" class="carousel slide">
                        <ol class="carousel-indicators">
                           <li data-target="#banner1" data-slide-to="0" class="active"></li>
                           <li data-target="#banner1" data-slide-to="1"></li>
                           <li data-target="#banner1" data-slide-to="2"></li>
                        </ol>
                        <div class="carousel-inner">
                           <!-- first slide -->
                           <div class="carousel-item active">
                              <div class="carousel-caption relative">
                                 <div class="row">
                                    <div class="col-md-6">
                                       <div class="dream">
                                          <h1>
                                             PowerFul <br>HOSTING <br>Your dream <br>website
                                          </h1>
                                          <a class="read_more" href="/register">Get Stared</a>    
                                          <a class="read_more" href="/contact">Contact Us</a>
                                       </div>
                                    </div>
                                    <div class="col-md-6">
                                       <div class="dream_img">
                                          <figure><img src="{{ url_for('static', filename = 'images/dream_img.png')}}" alt="#"/></figure>
                                       </div>
                                    </div>
                                 </div>
                              </div>
                           </div>
                           <!-- second slide -->
                           <div class="carousel-item">
                              <div class="carousel-caption relative">
                                 <div class="row">
                                    <div class="col-md-6">
                                       <div class="dream">
                                          <h1>
                                             PowerFul <br>HOSTING <br>Your dream <br>website
                                          </h1>
                                          <a class="read_more" href="/register">Get Stared</a>    
                                          <a class="read_more" href="/contact">Contact Us</a>
                                       </div>
                                    </div>
                                    <div class="col-md-6">
                                       <div class="dream_img">
                                          <figure><img src="{{ url_for('static', filename = 'images/dream_img.png')}}" alt="#"/></figure>
                                       </div>
                                    </div>
                                 </div>
                              </div>
                           </div>
                           <!-- third slide-->
                           <div class="carousel-item">
                              <div class="carousel-caption relative">
                                 <div class="row">
                                    <div class="col-md-6">
                                       <div class="dream">
                                          <h1>
                                             PowerFul <br>HOSTING <br>Your dream <br>website
                                          </h1>
                                          <a class="read_more" href="/register">Get Stared</a>    
                                          <a class="read_more" href="/contact">Contact Us</a>
                                       </div>
                                    </div>
                                    <div class="col-md-6">
                                       <div class="dream_img">
                                          <figure><img src="{{ url_for('static', filename = 'images/dream_img.png')}}" alt="#"/></figure>
                                       </div>
                                    </div>
                                 </div>
                              </div>
                           </div>
                        </div>
                        <!-- controls -->
                        <a class="carousel-control-prev" href="#banner1" role="button" data-slide="prev">
                        <i class="fa fa-arrow-left" aria-hidden="true"></i>
                        <span class="sr-only">Previous</span>
                        </a>
                        <a class="carousel-control-next" href="#banner1" role="button" data-slide="next">
                        <i class="fa fa-arrow-right" aria-hidden="true"></i>
                        <span class="sr-only">Next</span>
                        </a>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </div>
      <!-- end banner -->
      
{%endblock%}

first/templates/post.html
{%extends "secondback.html"%}
{%block content%}
 
    <article class="media content-section">
        <img src="{{ url_for('static', filename = 'profile_pic/' + post.author.image_file) }}" alt="##" class="rounded-circle article-img">
        <div class="media-body">
            <div class="article-metadata">
                <a href="{{ url_for('users.user_posts', username=post.author.username)}}" class="mr-2">{{ post.author.username }}</a>
                <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
                {% if post.author == current_user%}
                <div>
                    <a href="{{ url_for('posts.update_post', post_id=post.id)}}" class="btn btn-secondary btn-sm mt-1 mb-1">Update</a>
                    <form action="{{ url_for('posts.delete_post', post_id=post.id)}}" method = "POST">
                        <input type="submit" class="btn btn-danger" value="Delete">

                    </form>
                    
                </div>
                {%endif%}
            </div>
            <h2 class="article-title">{{ post.title}}</h2>
            <p class="article-content">{{ post.content}}</p>
        </div>
    </article>
    
{%endblock%}

first/templates/user_posts.html
{%extends "secondback.html"%}
{%block content%}
<h1 class="mb-3">Posts by {{ user.username}} ({{ posts.total}})</h1>
    {% for post in posts.items%}
    <article class="media content-section">
        <img src="{{ url_for('static', filename = 'profile_pic/' + post.author.image_file) }}" alt="##" class="rounded-circle article-img">
        <div class="media-body">
            <div class="article-metadata">
                <a href="{{ url_for('users.user_posts', username=post.author.username)}}" class="mr-2">{{ post.author.username }}</a>
                <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
            </div>
            <h2><a href="{{ url_for('posts.post', post_id=post.id)}}" class="article-title">{{ post.title}}</a></h2>
            <p class="article-content">{{ post.content}}</p>
        </div>
    </article>
    {%endfor%}
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
    {%if page_num%}
        {% if posts.page == page_num%}
        <a class="btn btn-info mb-4" href="{{ url_for('users.user_posts',username = user.username, page = page_num)}}"></a>
        {%else%}
        <a class="btn btn-outline-info mb-4" href="{{url_for('posts.user_posts',username = user.username, page = page_num)}}"></a>
        {%endif%}
    {%else%}
    ...
    {%endif%}
    {%endfor%}     
{%endblock%}